tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "cntlm", restart_service: true
brew "cowsay"
brew "git"
brew "gnupg"
brew "goenv"
brew "nkf"
brew "perl-build"
brew "plenv"
brew "qrencode"
brew "sbtenv"
brew "scalaenv"
brew "sqlite"
brew "wget"
